apiVersion: kubepkg.dev/v1alpha1
kind: Recipe
metadata:
  name: kyverno
  annotations:
    kubepkg.dev/description: "Policy engine: validate, mutate and generate resources with policies as Kubernetes resources"
    kubepkg.dev/home: https://kyverno.io/
spec:
  version: 1.19.1
  build: 2
  sources:
    upstream:
      chart:
        repository: https://kyverno.github.io/kyverno
        name: kyverno
        version: "3.9.1"
        digest: sha256:7b7fe51a431b5b133b0ce7eb9dcb222b6a37fb967c163223cf480054ad14d752
  charts:
    kyverno:
      from: [upstream]
  package:
    images:   # pinned with kubepkg images
      - ghcr.io/kyverno/readiness-checker:latest@sha256:57588e698a0c322e43b4b8bb61fe5256fd4a47e6216057d44f43a39a2c2f1e45
      - ghcr.io/kyverno/readiness-checker:v1.19.1@sha256:31bb42ce7f5b2e27c1cf633aeff4f0cad1f5bb63761e2cb09f0e25cdd26572bf
      - reg.kyverno.io/kyverno/background-controller:v1.19.1@sha256:8f1e9143373a27578cafc2d28d2c66ba0926c63b4c77e63de8d2fdd4a122859f
      - reg.kyverno.io/kyverno/cleanup-controller:v1.19.1@sha256:67a48e62a8d8f8120c86914ff822b90017c54054c7b64ef8a1555645e9d9761e
      - reg.kyverno.io/kyverno/kyverno-cli:v1.19.1@sha256:ced7b2be0b04250cabfe695f15307f69eb715fe23234816388af4f3812915b2a
      - reg.kyverno.io/kyverno/kyverno:v1.19.1@sha256:b31d8511ae5fd6010e2a01ea72ebae08eb82fa51d91af14a1d9fe989949b4edb
      - reg.kyverno.io/kyverno/kyvernopre:v1.19.1@sha256:c25c47461f06f2845a48c319ae86fbbc1730a7b9ed5b701889c9dc1f9ee94b09
      - reg.kyverno.io/kyverno/reports-controller:v1.19.1@sha256:c0eee97b9b44a0dd35805d56b358fa52548480f79d4944602b9609538eccd64c
    provides: [kyverno, policy-engine]
    crds:
      - cleanuppolicies.kyverno.io
      - clustercleanuppolicies.kyverno.io
      - clusterephemeralreports.reports.kyverno.io
      - clusterpolicies.kyverno.io
      - clusterpolicyreports.wgpolicyk8s.io
      - deletingpolicies.policies.kyverno.io
      - ephemeralreports.reports.kyverno.io
      - generatingpolicies.policies.kyverno.io
      - globalcontextentries.kyverno.io
      - imagevalidatingpolicies.policies.kyverno.io
      - mutatingpolicies.policies.kyverno.io
      - namespaceddeletingpolicies.policies.kyverno.io
      - namespacedgeneratingpolicies.policies.kyverno.io
      - namespacedimagevalidatingpolicies.policies.kyverno.io
      - namespacedmutatingpolicies.policies.kyverno.io
      - namespacedvalidatingpolicies.policies.kyverno.io
      - policies.kyverno.io
      - policyexceptions.kyverno.io
      - policyexceptions.policies.kyverno.io
      - policyreports.wgpolicyk8s.io
      - updaterequests.kyverno.io
      - validatingpolicies.policies.kyverno.io
    rollback:
      safe: false   # policies and reports live in its CRDs
    variants:
      - name: default
        components:
          - name: kyverno
            path: kyverno
            install: {namespace: kyverno}
